name: Test application generation

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  formatting:
    name: Formatting check
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Slack
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#version-control'
          message: Starting formatting checks
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run prettier check
        id: prettier-check
        run: yarn prettier:check

      - name: Run eslint check
        id: eslint-check
        run: yarn eslint:format

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#version-control'
        if: always()

  tests:
    name: Tests - jest
    needs: [formatting]
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Slack
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#version-control'
          message: Starting tests
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:ci
        env:
          CI: true

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#version-control'
        if: always()

  builds:
    name: Builds - nextjs & storybook
    needs: [tests]
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Slack
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#version-control'
          message: Starting builds
        if: always()

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build nextjs
        id: nextjs-build
        run: yarn build
        env:
          CI: true
          RESEND_API_KEY: "string"

      - name: Build storybook
        id: storybook-build
        run: yarn storybook:build
        env:
          CI: true

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#version-control'
        if: always()
